#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main(){
    // pseudo-random number generator = a set of random values that are generated by a deterministic process
    // rand() = generates a random number between 0 and RAND_MAX(32767)
    // srand() = seed the random number generator
    // time() = returns the current time of the system
    // NULL = pointer to the location of the memory address
    


    srand(time(0)); // seed the random number generator

    int number1 = (rand()%6 +1); // generate a random number between 1 and 6
    int number2 = (rand()%6 +1);
    int number3 = (rand()%6 +1);

    printf("%d\n", number1);
    printf("%d\n", number2);
    printf("%d\n", number3);

}
